dist: trusty
language: python
python:
- '2.7'
- pypy
- pypy-5.3.1
addons:
  sonarcloud:
    organization: "foxey"
    token:
      secure: "YlMRMm/0Ac82BykIS6LgKzY7argwJsnynXa3sml1kdrFBmeRrI+eSUrT/44xAjRed571XcPQ56VFlZnIr0ebGavgTdSinHpWE2Wuf6/OdrNBHsu96j23xKMtAu7w9qOAcJx/sjQPzSpXztvKqz31XhkxJn7kluuUgeILZmp5vh57eUTzuf4Th8YjopCZ11w/xj//t/SjTQ2jFvLIxY966FDlBam//Sqretf2ym/8pA2EoWbJK4SXYXD1ZumXgGxnj+4ZSTlTaOL7oMuncZMRiH+3Z8byQbZXkdhN5XG0D/lnNdP+wR50PFZMM0C1FA7l6wCs12F8XL5sBPcA88ORLqv9FXuzelJnk3M+p8T2Cbl4S+MMbJef/3MMJGQzZoqk0bHs22cZDaA6nMSPxafzzO0HXcQvgTNyEhKKPDHyxD/DniBavFfbDkOzC7RST4ThaX2yR6PVx64rQAulZGSjvuujoP0DqhFIWAgp+ekYLXNxQDQdMgtxK+eb9yRHy7f2zJz4pBJHqyui+7FKMhIt1W8pyhRrepItpneTXKF5DNQi7ng5xZjYz4cXM4rH3QPfeM9RLul4ntKemSj+mo8qAeDPC1hktD5Fqqw+wi2xCNMU+hHWjSWo9PqhnPtVuia20atHidVO3muLOtIsJcmhC+R/chUD+bBKwTvBoiCCk6A="
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y zlib1g-dev libjpeg-dev python-dev swig
- sudo pip install -U pip
install:
- python setup.py install
script:
- python setup.py test
- sonar-scanner
deploy:
  provider: pypi
  user: foxey
  password:
    secure: "Ks653sXOLmuC/F46s/xYlHZUD2dCMkeKhijBBSFOx/zwhvmGEPVWr6fku5OfzzNONo7wwVPtoO9i6Z3LPv1OV99JP2/j9GHA/86v5puigohZuji9AuUJtk3douoMnbsn+T9QYONzNfHoIBTBU5+c71RpDA/FlfgXUu4gIXbQxhxGSQZ0CWylY18CIOpXbjqbFP7i+ueS5Lj48iwQcKQU6ULqxVlgdnYIl6HDcz3WuS0GdWah4YOwluHI7c/rY4q4ARvbUg9sGmLfiAPQ9xUV/YWOzSaXfdiY5bayhXHIRBX8V/Ftgr1W60cGOhOq+/PF9sr6j+WpuBH/adjUX6VconpBTE4cAd6vT6BUuC/R4apWr+Tnt39LNvr7mCT1w2ERbJI5C/RhIq2WQedUJXxWIyuVaQrLH3tEq75byFC489HbBMD9JqKdGOP6O7frRbR85W7UEcpL9nPmMp0R3LxpzGstAWTZ+GpovMWMSrlFGxF1EgcGh60OBagfiGq/uDIRM7JXPpET+SlGmmNgAINZ2KOEeYxxQ1qdGLfwoYJEIMaVszD8CIa+Ddp42joWptFXRpogZQe7CjT8z0kbA8lhrUtBmnewErEvl8di4oWxg7+5bRJGEWlWv7YouQFZxJ8mSRVYaVKRLWBxJ07sHwhwWgEkEo1Ejtz7RAyqH0sGIv4="
  repo: foxey/volumio-buddy
  distributions: sdist
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
